### ISSUE TITLE
All Scenarios and Steps are under a single test when using GenericDriver with SpecFlow plugin

### ISSUE THREAD

**Issue by SabotageAndi** [testproject-io/csharp-opensdk#106]
Repro- Project: https://github.com/SabotageAndi/TestProjectSample

It is using SpecFlow with a GenericDriver for the OpenSDK (0.65.1.294-rc).
In the report on Testproject.io I get both scenarios under one test, which lists all the steps:

![image](https://user-images.githubusercontent.com/859801/108214017-f273a980-712f-11eb-93a8-7501b2675f6c.png)

I have it working in another example, but I won't get it to work in this one.

@basdijkstra any ideas what I am making wrong?

**Comment by basdijkstra** [comment]
No, but that doesn't look right.. I'll dive into it. Again, got some other things to wrap up first, though.

**Comment by SabotageAndi** [comment]
Not to put more pressure on you @basdijkstra, but I have next Wednesday a Webinar where I want to show the SpecFlow & TestProject integration.
Do you see a chance to have a look at this in time for it?

**Comment by basdijkstra** [comment]
I can have a look tomorrow morning. Not sure how much time it will take to fix this.

**Comment by basdijkstra** [comment]
I'm able to reproduce this on my machine, I'll dive into it later this morning to fix it.

**Comment by basdijkstra** [comment]
Ah, this is easier to explain than I thought.

The `GenericDriver` does not automatically report new tests (or in this case, scenarios). That's done by design, because there are no WebDriver commands to trace and inspect. When you're using the `GenericDriver`, the user is responsible for reporting steps and tests themselves. As long as you don't do that, all steps will end up in the same test, which will be named `Test` because no actual test name is inferred.

We might improve this in the future, but for now this is how the `GenericDriver` works. When you're using it with SpecFlow, there's an easy workaround. When I add this `[AfterScenario]` hook:

```csharp
[AfterScenario]
public void CloseDriver()
{
    this.genericDriver.Report().Test(this.scenarioContext.ScenarioInfo.Title, true);

    this.genericDriver.Quit();
}
```
The report looks like this:

![image](https://user-images.githubusercontent.com/10740451/108326423-82fec800-71ca-11eb-9ce0-11e91b923c67.png)

Of course this requires you to inject the `ScenarioContext` into your hook class as well. Oh, and please ensure to always call `driver.Quit()` as that performs required shutdown and report finalizing logic. 

@SabotageAndi, if you still feel that the plugin implementation (or that of the `GenericDriver` should be improved, I'm happy to take suggestions,  but at least you have a way to make it work now.

**Comment by SabotageAndi** [comment]
Thanks, your code worked.
I adjusted it slightly to pass the right value to the passed parameter

``` csharp
[AfterScenario]
public void CloseDriver()
{
    _genericDriver.Report().Test(_scenarioContext.ScenarioInfo.Title, _scenarioContext.TestError is null);
    _genericDriver.Quit();
}
```

Is this something I overlooked in the documentation?

**Comment by basdijkstra** [comment]
> Is this something I overlooked in the documentation?

There might be some room for improvement there.. I'll see if I can work that in the next time I do some work on the docs.
