### ISSUE TITLE
[Web] Wrong step text for displayed in the report.

### ISSUE THREAD

**Issue by dorbenzvi** [testproject-io/csharp-opensdk#132]
When running a step with Displayed on the element, the on the report its coverts to Execute Script.

Code:

```
  Assert.IsTrue(this.driver.FindElement(By.CssSelector("#greetings")).Displayed);
```

Report:

![image](https://user-images.githubusercontent.com/55704483/110243409-e591eb00-7f62-11eb-8753-cf30e468cfe3.png)

**Comment by basdijkstra** [comment]
That's not a bug, it's a feature.

The W3C command executed when you use the .Displayed property is `executeScript` (a bit of JavaScript is executed to determine whether an element is visible), so that's what you'll see in the report.

I can't / don't want to change that, as that would mean parsing the JavaScript being executed to see which command is behind it, and that's a can of worms I really, really don't want to open..

**Comment by basdijkstra** [comment]
Closing this issue due for inactivity and because it's a 'won't fix'. @dorbenzvi, feel free to reopen it and add your comments as to why you think it should be reopened if you want to.
