### ISSUE TITLE
Adding ImplicitWait to driver reported as a separated test.

### ISSUE THREAD

**Issue by dorbenzvi** [testproject-io/csharp-opensdk#141]
This is happening because of the ImplicitWait time sets to the driver.
Base:

```
using System;
using TestProject.OpenSDK.Drivers.Web;

namespace XUnitTestProject2
{
    public class BaseTest 
    {
        public ChromeDriver Driver;

        public BaseTest()
        {
            Driver = new ChromeDriver(projectName: "PANDA2",token: "TOEKN_HERE");
            Driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(3000);
        }

   
    }
}
```

Test:

```
namespace XUnitTestProject2
{
    using OpenQA.Selenium;
    using TestProject.OpenSDK.Drivers.Generic;
    using TestProject.OpenSDK.Drivers.Web;
    using Xunit;
    using TestProject.OpenSDK.Internal.CallStackAnalysis;
    using Xunit.Abstractions;
    public class OpenSdk : BaseTest
    {
        private readonly ITestOutputHelper _testOutputHelper;
        private const string XUnitNamespace = "XUnit";
        private const string TestNameProperty = "DisplayName";
        private static readonly string[] AttributeNames = { "Fact", "Theory" };
        [Fact]
        public void Test1()
        {
            //var Driver = new ChromeDriver();

            Driver.Navigate().GoToUrl("https://example.testproject.io");
            Driver.FindElement(By.CssSelector("#name")).SendKeys("John Smith");
            Driver.FindElement(By.CssSelector("#password")).SendKeys("12345");
            Driver.FindElement(By.CssSelector("#login")).Click();
            Assert.True(Driver.FindElement(By.CssSelector("#greetings")).Displayed);

            Driver.Quit();
        }


        public OpenSdk(ITestOutputHelper testOutputHelper)
        {
            _testOutputHelper = testOutputHelper;
        }


    }
}

```

![image](https://user-images.githubusercontent.com/55704483/111615382-56e65f00-87e9-11eb-81dc-a8db3e1417da.png)

**Comment by basdijkstra** [comment]
I suspect that this will be resolved when #140 is addressed, but happy to keep it open as a separate issue for now.

**Comment by basdijkstra** [comment]
See also the explanation for #140. There's no way to determine that the code executed in the base class actually belongs to a test method in the `OpenSdk` class, because we're in a different class without any reference to xUnit and the `OpenSdk` class does not have any class-level annotations that we could use..

If xUnit would support test-level setup and teardown methods, it would be an entirely different story, but that goes against their philosophy. Unfortunately, that means there's no way to fix this at the moment.

**Comment by kishangupta-15** [comment]
@basdijkstra For #140, as you suggested, one possible workaround is to specify job name at the time of driver creation. Is there a work around for this too? Otherwise, the TestProject's reporting feature becomes useless as random tests gets reported. So, if someone ran 20 tests, 40 will be reported and possibly more if additional driver configurations are added.

**Comment by basdijkstra** [comment]
@kishangupta-15 not really. I see not having setup and teardown hooks as a drawback of xUnit, but its creators obviously think otherwise...

If you're not really fixed on xUnit I'd recommend switching to NUnit and moving all the driver creation and configuration to a setup method.

If you do need to use xUnit you could do the driver configuration inside the test method themselves. That does result in some code duplication, though.

**Comment by kishangupta-15** [comment]
@basdijkstra Well, that's a bummer because we are in fact fixed on xUnit as this is the standard test framework for all the development related activities in C#.

This really going to put a drag for all folks using xUnit. I was really hoping for a resolution for this

**Comment by basdijkstra** [comment]
I know, but as far as I can see I'm really bound by the limitations of the unit testing framework here.

Maybe @s-glatshtein has an idea for a resolution here?

**Comment by s-glatshtein** [comment]
At first glance i don't see a way to detect the test method when the constructor is called.
My best idea would be disabling reports in that constructor, so that step isn't reported. It doesn't feel like an integrated part of the test.

**Comment by basdijkstra** [comment]
@kishangupta-15 do you agree? I really don't see a way to resolve this at the moment.

**Comment by kishangupta-15** [comment]
@basdijkstra seems like the only solution. But when I disable the reports in the constructor, is any there any way to re enable them later in the test?

**Comment by basdijkstra** [comment]
Sure.

```csharp
ChromeDriver driver = new ChromeDriver(chromeOptions: new ChromeOptions());
driver.Report().DisableCommandReports(DriverCommandsFilter.All);
// no driver commands will be reported here
driver.Report().DisableCommandReports(DriverCommandsFilter.None);
// from here on all driver commands will be reported again
```

**Comment by kishangupta-15** [comment]
@basdijkstra, @s-glatshtein  I tried it out. Unfortunately, it still reports the extra test with marking it as skipped.

![image](https://user-images.githubusercontent.com/54025467/111968039-c2e50200-8b1e-11eb-903f-fb9470ea3fa1.png)

Full report attached here:
[FtpKeysPageTests-Job-Report-22-3-2021+09-20-16-full.pdf](https://github.com/testproject-io/csharp-opensdk/files/6180929/FtpKeysPageTests-Job-Report-22-3-2021%2B09-20-16-full.pdf)

**Comment by basdijkstra** [comment]
PR #153 also solves this issue. The report now looks like this:

![image](https://user-images.githubusercontent.com/10740451/112194424-1f245080-8c09-11eb-9d4b-a99915b34564.png)

As you can see, the timeout call is reported as part of the test, instead of in a separate method. Please retest with the latest prerelease once this PR has been merged.

**Comment by basdijkstra** [comment]
PR #153 has been merged and released in https://www.nuget.org/packages/TestProject.OpenSDK/0.66.0.372-rc. Please retest and close this issue when you're happy with the result.

**Comment by kishangupta-15** [comment]
I have checked and it is working fine now. Thanks a ton for resolving this, it makes our life a lot easier. I have checked this by adding driver.Manage().Window.Maximize() as well and it is also getting reported in the test itself.

![image](https://user-images.githubusercontent.com/54025467/112505325-af51c980-8db2-11eb-9a33-be72062acf7b.png)

@basdijkstra i am assuming that this is how it will work for other driver configuration settings as well. Please correct me, if I am wrong. And please assign it to Dor for closure as he is the creator of this issue and I don't have the permission to close this issue.

@dorbenzvi Since you are the creator of this issue, could you please close it as I don't have the permission to do it.

Thank you Bas and Dor

**Comment by basdijkstra** [comment]
Yes, it works like this for all driver commands.

Let me close the issue for you, thanks for confirming. And you're welcome :)
