### ISSUE TITLE
output isn't written to console in xUnit tests

### ISSUE THREAD

**Issue by s-glatshtein** [testproject-io/csharp-opensdk#229]
xUnit seem to override the standard console output, preventing important information such as the report URL from being shown to the user. We should investigate how to integrate with xUnit logger

**Comment by kishangupta-15** [comment]
@s-glatshtein Hello Shai, I had a small request, if you could add this bug the priority list, that would be really great. It will make debugging a lot easier.

**Comment by s-glatshtein** [comment]
It is in the priority list. The solution however is not as straight forward as i hoped so it is taking a little longer than expected.

**Comment by kishangupta-15** [comment]
@s-glatshtein  - Hello Shai, hope you are doing good. Could you please provide an example on how to use xUnit Logging with OpenSDK because I tried with the regular ITestOutputHelper class from xUnit, it is not working for me. I am making a mistake somewhere. An example would definitely help with this.

**Comment by s-glatshtein** [comment]
Hi @kishangupta-15. Please refer to this section of the readme for more information: https://github.com/testproject-io/csharp-opensdk#capturing-output-in-xunit-tests
